<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <OutputType Condition="'$(TargetFramework)' == 'net8.0-windows'">WinExe</OutputType>
    <UseWPF Condition="'$(TargetFramework)' == 'net8.0-windows'">true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>BalloonPdf.App</RootNamespace>
    <AssemblyName>BalloonPdf.App</AssemblyName>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <Compile Remove="App.xaml.cs;MainWindow.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
    <PackageReference Include="PdfSharp" Version="6.2.4" />
  </ItemGroup>
</Project>
